from PySide6 import QtCore, QtGui, QtWidgets
from crop_widget import Crop_frame

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1024, 570)
        MainWindow.setFixedWidth(1024)
        MainWindow.setFixedHeight(570)

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 253, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 253, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 253, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 253, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 253, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 125, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        MainWindow.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(7, -2, 1010, 520))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.image_1 = QtWidgets.QLabel(self.tab_1)
        self.image_1.setGeometry(QtCore.QRect(30, 70, 300, 300))
        self.image_1.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.image_1.setText("")
        # self.image_1.setPixmap(QtGui.QPixmap(""))
        self.image_1.setScaledContents(True)
        self.image_1.setObjectName("image_1")
        self.image_2 = QtWidgets.QLabel(self.tab_1)
        self.image_2.setGeometry(QtCore.QRect(350, 70, 300, 300))
        self.image_2.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.image_2.setText("")
        self.image_2.setPixmap(QtGui.QPixmap(""))
        self.image_2.setScaledContents(True)
        self.image_2.setObjectName("image_2")
        self.image_3 = QtWidgets.QLabel(self.tab_1)
        self.image_3.setGeometry(QtCore.QRect(670, 70, 300, 300))
        self.image_3.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.image_3.setText("")
        self.image_3.setPixmap(QtGui.QPixmap(""))
        self.image_3.setScaledContents(True)
        self.image_3.setObjectName("image_3")
        self.text_1 = QtWidgets.QLabel(self.tab_1)
        self.text_1.setGeometry(QtCore.QRect(130, 390, 100, 70))
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QLabel(self.tab_1)
        self.text_2.setGeometry(QtCore.QRect(460, 390, 100, 70))
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QLabel(self.tab_1)
        self.text_3.setGeometry(QtCore.QRect(790, 390, 100, 70))
        self.text_3.setObjectName("text_3")
        self.radioButton_1 = QtWidgets.QRadioButton(self.tab_1)
        self.radioButton_1.setGeometry(QtCore.QRect(160, 40, 40, 20))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_1)
        self.radioButton_2.setGeometry(QtCore.QRect(480, 40, 40, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_1)
        self.radioButton_3.setGeometry(QtCore.QRect(800, 40, 40, 20))
        self.radioButton_3.setObjectName("radioButton_3")

        self.undo_pushButton = QtWidgets.QPushButton(self.tab_1)
        self.undo_pushButton.setGeometry(QtCore.QRect(900, 450, 30, 30))
        self.undo_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/yileicao/Downloads/fugue-icons-3/icons/arrow-curve-180-left.png"),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.undo_pushButton.setIcon(icon)
        self.undo_pushButton.setObjectName("undo_pushButton")

        self.redo_pushButton = QtWidgets.QPushButton(self.tab_1)
        self.redo_pushButton.setGeometry(QtCore.QRect(950, 450, 30, 30))
        self.redo_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/yileicao/Downloads/fugue-icons-3/icons/arrow-curve.png"),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.redo_pushButton.setIcon(icon)
        self.redo_pushButton.setObjectName("undo_redoButton")
        self.tabWidget.addTab(self.tab_1, "")

        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tab_2.setObjectName("tab_2")
        self.enhanced_radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.enhanced_radioButton.setGeometry(QtCore.QRect(810, 110, 100, 20))
        self.enhanced_radioButton.setObjectName("enhanced_radioButton")
        self.raw_frame = QtWidgets.QLabel(self.tab_2)
        self.raw_frame.setGeometry(QtCore.QRect(490, 140, 230, 230))
        self.raw_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.raw_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.raw_frame.setPixmap(QtGui.QPixmap(""))
        self.raw_frame.setScaledContents(True)
        self.raw_frame.setObjectName("raw_frame")
        self.enhanced_frame_label = QtWidgets.QLabel(self.tab_2)
        self.enhanced_frame_label.setGeometry(QtCore.QRect(810, 375, 120, 40))
        self.enhanced_frame_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.enhanced_frame_label.setObjectName("enhanced_frame_label")
        self.raw_radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.raw_radioButton.setGeometry(QtCore.QRect(550, 110, 100, 20))
        self.raw_radioButton.setObjectName("raw_radioButton")


        self.horizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 420, 290, 25))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)


        self.video_information_label = QtWidgets.QLabel(self.tab_2)
        self.video_information_label.setEnabled(True)
        self.video_information_label.setGeometry(QtCore.QRect(490, 20, 490, 71))
        self.video_information_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.video_information_label.setObjectName("video_information_label")
        self.enhanced_frame = QtWidgets.QLabel(self.tab_2)
        self.enhanced_frame.setGeometry(QtCore.QRect(750, 140, 230, 230))
        self.enhanced_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.enhanced_frame.setObjectName("enhanced_frame")

        self.raw_frame_label = QtWidgets.QLabel(self.tab_2)
        self.raw_frame_label.setGeometry(QtCore.QRect(550, 375, 120, 40))
        self.raw_frame_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.raw_frame_label.setObjectName("raw_frame_label")

        # set arrow buttons around slider
        self.forward_pushButton = QtWidgets.QPushButton(self.tab_2)
        self.forward_pushButton.setGeometry(QtCore.QRect(50, 420, 30, 30))
        self.forward_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/yileicao/Downloads/fugue-icons-3/icons/ui-button-navigation-back.png"),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.forward_pushButton.setIcon(icon)
        self.forward_pushButton.setObjectName("forward_pushButton")



        self.afterward_pushButton = QtWidgets.QPushButton(self.tab_2)
        self.afterward_pushButton.setGeometry(QtCore.QRect(420, 420, 30, 30))
        self.afterward_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/yileicao/Downloads/fugue-icons-3/icons/ui-button-navigation.png"),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.afterward_pushButton.setIcon(icon)
        self.afterward_pushButton.setObjectName("afterward_pushButton")



        self.pushButton_A = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_A.setGeometry(QtCore.QRect(570, 440, 100, 30))
        self.pushButton_A.setObjectName("pushButton_A")

        self.pushButton_B = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_B.setGeometry(QtCore.QRect(685, 440, 100, 30))
        self.pushButton_B.setObjectName("pushButton_B")

        self.pushButton_C = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_C.setGeometry(QtCore.QRect(800, 440, 100, 30))
        self.pushButton_C.setObjectName("pushButton_C")



        self.big_frame = QtWidgets.QLabel(self.tab_2)
        self.big_frame.setGeometry(QtCore.QRect(50, 10, 400, 400))
        self.big_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.big_frame.setText("")
        self.big_frame.setPixmap(QtGui.QPixmap(""))
        self.big_frame.setScaledContents(True)
        self.big_frame.setObjectName("big_frame")

        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(220, 450, 60, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.goto_pushButton = QtWidgets.QPushButton(self.tab_2)
        self.goto_pushButton.setGeometry(QtCore.QRect(290, 450, 60, 30))
        self.goto_pushButton.setObjectName("goto_pushButton")

        self.pushButton_gotoA = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_gotoA.setGeometry(QtCore.QRect(360, 450, 31, 32))
        self.pushButton_gotoA.setObjectName("pushButton_gotoA")
        self.pushButton_gotob = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_gotob.setGeometry(QtCore.QRect(390, 450, 31, 32))
        self.pushButton_gotob.setObjectName("pushButton_gotob")
        self.pushButton_gotoc = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_gotoc.setGeometry(QtCore.QRect(420, 450, 31, 32))
        self.pushButton_gotoc.setObjectName("pushButton_gotoc")

        self.pushButton_enhance = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_enhance.setGeometry(QtCore.QRect(80, 450, 80, 32))
        self.pushButton_enhance.setObjectName("pushButton_enhance")

        self.tabWidget.addTab(self.tab_2, "")



        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        # self.crop_frame = QtWidgets.QLabel(self.tab_3)
        self.crop_frame = Crop_frame(self.tab_3)
        self.crop_frame.setGeometry(QtCore.QRect(30, 10, 450, 450))
        self.crop_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.crop_frame.setPixmap(QtGui.QPixmap(""))
        self.crop_frame.setScaledContents(True)
        self.crop_frame.setObjectName("crop_frame")

        self.cropButton = QtWidgets.QPushButton(self.tab_3)
        self.cropButton.setGeometry(QtCore.QRect(310, 460, 80, 30))
        self.cropButton.setObjectName("crop_button")

        self.confirmButton = QtWidgets.QPushButton(self.tab_3)
        self.confirmButton.setGeometry(QtCore.QRect(390, 460, 80, 30))
        self.confirmButton.setObjectName("confirm_button")

        self.enhanced_frame_2 = QtWidgets.QLabel(self.tab_3)
        self.enhanced_frame_2.setGeometry(QtCore.QRect(760, 100, 230, 230))
        self.enhanced_frame_2.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.enhanced_frame_2.setObjectName("enhanced_frame_2")
        self.raw_frame_2 = QtWidgets.QLabel(self.tab_3)
        self.raw_frame_2.setGeometry(QtCore.QRect(510, 100, 230, 230))
        self.raw_frame_2.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.raw_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.raw_frame_2.setScaledContents(True)
        self.raw_frame_2.setObjectName("raw_frame_2")
        self.raw_frame_label_2 = QtWidgets.QLabel(self.tab_3)
        self.raw_frame_label_2.setGeometry(QtCore.QRect(565, 340, 120, 51))
        self.raw_frame_label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.raw_frame_label_2.setObjectName("raw_frame_label_2")
        self.enhanced_frame_label_2 = QtWidgets.QLabel(self.tab_3)
        self.enhanced_frame_label_2.setGeometry(QtCore.QRect(815, 340, 120, 51))
        self.enhanced_frame_label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.enhanced_frame_label_2.setObjectName("enhanced_frame_label_2")
        self.save_raw_rb = QtWidgets.QRadioButton(self.tab_3)
        self.save_raw_rb.setGeometry(QtCore.QRect(580, 50, 150, 20))
        self.save_raw_rb.setObjectName("save_raw_rb")
        self.save_enhance_rb = QtWidgets.QRadioButton(self.tab_3)
        self.save_enhance_rb.setGeometry(QtCore.QRect(810, 50, 150, 20))
        self.save_enhance_rb.setObjectName("save_enhance_rb")
        self.save_pushButton = QtWidgets.QPushButton(self.tab_3)
        self.save_pushButton.setGeometry(QtCore.QRect(920, 420, 60, 30))
        self.save_pushButton.setObjectName("save_pushButton")
        self.crop_frame_label = QtWidgets.QLabel(self.tab_3)
        self.crop_frame_label.setGeometry(QtCore.QRect(490, 408, 111, 71))
        self.crop_frame_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.crop_frame_label.setObjectName("crop_frame_label")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave.setShortcut('Ctrl+S')
        self.actionSave.setStatusTip("Save cropped image")
        self.actionSave.triggered.connect(self.save_image)

        # Create Open action
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen.setShortcut('Ctrl+N')
        self.actionOpen.setStatusTip("Open new video file")
        self.actionOpen.triggered.connect(self.openCall)

        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose.setShortcut('Ctrl+C')
        self.actionClose.setStatusTip("Close programme")
        self.actionClose.triggered.connect(self.close)

        # Create Openfile action
        self.actionOpenFolder = QtGui.QAction(MainWindow)
        self.actionOpenFolder.setObjectName("actionOpenFolder")
        self.actionOpenFolder.setStatusTip("Open image folder")
        self.actionOpenFolder.triggered.connect(self.openFolderCall)


        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenFolder)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_1.setText(_translate("MainWindow", "TextLabel"))
        self.image_2.setText(_translate("MainWindow", "TextLabel"))
        self.image_3.setText(_translate("MainWindow", "TextLabel"))
        self.text_1.setText(_translate("MainWindow", "TextLabel"))
        self.text_2.setText(_translate("MainWindow", "TextLabel"))
        self.text_3.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_1.setText(_translate("MainWindow", "A"))
        self.radioButton_2.setText(_translate("MainWindow", "B"))
        self.radioButton_3.setText(_translate("MainWindow", "C"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "View"))
        self.enhanced_radioButton.setText(_translate("MainWindow", "Enhanced"))
        self.raw_radioButton.setText(_translate("MainWindow", "Raw"))
        self.video_information_label.setText(_translate("MainWindow", "Video Information"))
        self.raw_frame.setText(_translate("MainWindow", "raw frame"))
        self.enhanced_frame.setText(_translate("MainWindow", "Enhanced frame"))
        self.raw_frame_label.setText(_translate("MainWindow", "Raw frame information"))
        self.enhanced_frame_label.setText(_translate("MainWindow", "Enhanced frame information"))
        self.goto_pushButton.setText(_translate("MainWindow", "go to"))
        self.pushButton_A.setText(_translate("MainWindow", "Save to A"))
        self.pushButton_B.setText(_translate("MainWindow", "Save to B"))
        self.pushButton_C.setText(_translate("MainWindow", "Save to C"))

        self.pushButton_enhance.setText(_translate("MainWindow", "Enhance"))

        self.pushButton_gotoA.setText(_translate("MainWindow", "A"))
        self.pushButton_gotob.setText(_translate("MainWindow", "B"))
        self.pushButton_gotoc.setText(_translate("MainWindow", "C"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Select"))
        self.enhanced_frame_2.setText(_translate("MainWindow", "enhanced frame"))
        self.raw_frame_2.setText(_translate("MainWindow", "raw frame"))
        self.raw_frame_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.enhanced_frame_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.save_raw_rb.setText(_translate("MainWindow", "Select Raw"))
        self.save_enhance_rb.setText(_translate("MainWindow", "Select Enhanced"))
        self.save_pushButton.setText(_translate("MainWindow", "SAVE"))
        self.cropButton.setText(_translate("MainWindow", "Crop"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Crop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpenFolder.setText(_translate("MainWindow", "OpenFolder"))


